apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: huggingface-llama2
spec:
  supportedModelFormats:
    - name: huggingface
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: vllm/vllm-openai
      args:
        - "--model" 
        - "meta-llama/Llama-2-7b-chat-hf" 
        - "--disable-log-requests"
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: hf-token
      ports:
        - containerPort: 8000
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          cpu: 4
          memory: 16Gi
          nvidia.com/gpu: 1
  disabled: false
  multiModel: false
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-llama2
  annotations:
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    model:
      runtime: huggingface-llama2
      modelFormat:
        name: huggingface